version: '3.9'

services:
  bot:
    build: .
    command: python -m tgbot.main
    volumes:
      - .:/AiBot
    depends_on:
      - api
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./tgbot/.env

  api:
    build: .
    command: uvicorn fast.app.main:app --host 0.0.0.0 --port 8099
    ports:
      - "8099:8099"
    volumes:
      - .:/AiBot
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./fast/.env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
